name: Status Check Functions
on: [push]
run-name: Status Check Functions by @${{github.actor}}, ${{github.event_name}}
jobs:

  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on Failure
        if: failure()
        run: echo "Runs only on Failure"
      - name: Runs on Success
        # This is not needed (Default Behaviour)
        if: success()
        run: echo "Runs on Success"
      - name: Always Runs
        if: always()
        run: echo "Always Runss"
      - name: Runs when Cancelled
        if: cancelled()
        run: echo "Runs on Cancelled"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo "job-2"
