# Setting an Environment Variable
# echo "{environment_variable_name}={value}" >> "$GITHUB_ENV"

name: Setting Env Variables during the execution of a WF
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      job_level_env: Available to All steps in this Job
    steps:
      - name: Set ENV var
        run: |
          echo "NEW_ENV_VAR=$(date)" >> $GITHUB_ENV
          echo "job_level_env=$RANDOM" >> $GITHUB_ENV
          echo $job_level_env
      - name: Display all ENV Vars
        run: |
          echo $job_level_env
          echo $NEW_ENV_VAR


#   MultiLine Strings Syntax:
#   {name}<<{delimiter}
#   {value}
#   {delimiter}

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Multiline Strings
        run: |
          DELIMITER=1234
          echo "RANDOM_JOKE<<$DELIMITER" >> "$GITHUB_ENV"
          echo "Here is a Joke: " >> "$GITHUB_ENV"
          curl -s https://icanhazdadjoke.com/ >> $GITHUB_ENV
          echo "" >> "$GITHUB_ENV"
          echo "$DELIMITER" >> "$GITHUB_ENV"
      - name: Show me a Joke
        run: echo $RANDOM_JOKE


#Proper Multiline Syntax:
# - name: Set multiline env
#   run: |
#     echo "VAR_NAME<<EOF" >> $GITHUB_ENV
#     echo "Line 1" >> $GITHUB_ENV
#     echo "Line 2" >> $GITHUB_ENV
#     echo "Line 3" >> $GITHUB_ENV
#     echo "EOF" >> $GITHUB_ENV