name: First Workflow
on: push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: run a echo command
        run: echo "Hello World"

      - name: run a second echo command
        run: echo "This is second time Hello World"

      - name: Multiline command
        run: |
          node -v
          npm -v
          git -v
        
      - name: the date
        run: date

  run-shell-commands-2:
    runs-on: ubuntu-latest
    steps:
      - name: get the present working directory
        run: pwd

      - name: get the current directory items
        run: ls -ltrah
  
  run-shell-commands-3:
    runs-on: ubuntu-latest
    steps:
      - name: create a file called sample.txt
        run: |
          whoami
          pwd
          echo "Hello World this is Thazeeb Khan" > sample.txt
          cat sample.txt
          pwd

      - name: get the file contents from the previous step (testing)
        run: cat sample.txt