name: Working Dirs and Shells
on: push
defaults:
  run:
    shell: bash
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display WD & List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: Changing Working Dir
              working-directory: /home/runner
              run: pwd
            - name: Overriding default Bash Shell to Python Shell
              shell: python
              run: |
                import platform
                print(platform.processor())

    display-wd-info-win-using-bash:
        runs-on: ubuntu-latest
        steps:
            - name: Display WD & List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

    display-wd-info-windows:
        runs-on: windows-latest
        defaults:
          run:
            shell: pwsh
        steps:
            - name: Display WD & List Files
              run: |
                Get-Location
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE